### PR TITLE
Nav style

### PR DESCRIPTION
**Pull request by Tarmstrong95**
Please leave a comment on what could be fixed, thank you.

### CODE REVIEW

**Comment by dxtrlws** [comment]
Is there going to be a logout button in the navbar as well?

**Comment by Tarmstrong95** [comment]
I would imagine the logout button would be in the same area as the other stuff here

if not, in the navbar is fine too

image

**Comment by Tarmstrong95** [comment]
Just let me know

**Comment by dxtrlws** [comment]
The side menu would be related to actions you can do within the app, so let's keep the logout button in the nav.

**Pull request merged**
